name: "publish"

# modified from https://github.com/tauri-apps/tauri-action/blob/dev/examples/publish-to-auto-release.yml

# Only trigger when manually triggered.
on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above)
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install bun
        run: npm install -g bun

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Print current directory
        run: pwd

      - name: move to led-matrix-gui directory
        run: cd ./nodejs/led-matrix-gui

      - name: Print current directory
        run: pwd

      - name: install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: led-matrix-gui-v__VERSION__
          releaseName: "LED Matrix GUI v__VERSION__"
          releaseBody: "See the assets to download and run this version of the app."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
